# Project information
site_name: "Aqua Docs"
site_description: "Documentation for Gridless, Seaworld, the Aqua API, and the Aqua ecosystem"
site_author: "Aqua Technologies"
site_url: "https://getaqua.github.io/docs/"

# Copyright
copyright: "&copy; 2022 Aqua Technologie"

# Repository
repo_name: "Documentation"
repo_url: "https://github.com/getaqua/docs"
edit_uri: "https://github.com/getaqua/docs/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "purple"
  features:
    - tabs
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  #- "assets/css/custom.css"
extra:
  #manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/getaqua"
    - icon: "fontawesome/brands/discord"
      link: "https://discord.gg/JREFswrhqD"

# Page tree
nav:
  - Contributors:
    - What to Change: contributing/change-what.md
  - Guides:
    - Third-Party Clients:
      - Authorization: guides/clientdev/authorization.md
    - Gridless:
      - Starting Gridless: guides/gridless/starting-gridless.md
  - Reference:
    - Gridless:
      - Errors: reference/gridless/errors.md
      - Scopes: reference/gridless/scopes.md
